HAI 1.2

  HOW IZ I CALCULATE_CIRCLE_PERIMETER YR RADIUS
    I HAS A RESULT

    BOTH SAEM RADIUS AN 0, O RLY?
      YA RLY, GTFO
      NO WAI
        RESULT R PRODUKT OF 6.28 AN RADIUS
        FOUND YR RESULT
    OIC
  IF U SAY SO

  I HAS A RADIUS
  I HAS A PERIMETER
  VISIBLE "GIMME RADIUS:"
  GIMMEH RADIUS

  RADIUS IS NOW A NUMBAR
  PERIMETER R I IZ CALCULATE_CIRCLE_PERIMETER YR RADIUS MKAY
  PERIMETER IS NOW A YARN
  VISIBLE "YER PERIMETER IZ " PERIMETER

KTHXBYE
