HAI 1.2

  HOW IZ I CALCULATE_CIRCLE_PERIMETER YR RADIUS
    BTW VISIBLE PRODUKT OF 6.28 AN RADIUS

    BTW RETURN A VALUE:
    FOUND YR PRODUKT OF 6.28 AN RADIUS

    BTW RETURN FROM THE FUNCTION:
    GTFO
  IF U SAY SO

  VISIBLE I IZ CALCULATE_CIRCLE_PERIMETER YR 10 MKAY

KTHXBYE
