HAI 1.2

  I HAS A VAR_A ITZ 5
  I HAS A VAR_B ITZ 10

  VAR_A R SUM OF VAR_A AN VAR_B   BTW 15

  VAR_B R DIFF OF VAR_A AN VAR_B    BTW 5

  VAR_A R DIFF OF VAR_A AN VAR_B    BTW 10

  VISIBLE "VAR_A: " VAR_A
  VISIBLE "VAR_B: " VAR_B

KTHXBYE
